"""Adding column on Characters, set nullable true on token

Revision ID: 82ff4662faa5
Revises: 
Create Date: 2022-08-18 11:10:22.089162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ff4662faa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###
