"""Change type of token

Revision ID: b3f91d7d23ea
Revises: 82ff4662faa5
Create Date: 2022-08-18 11:13:33.604310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f91d7d23ea'
down_revision = '82ff4662faa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
